name: Node C

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Update Server Repo
        uses: maddox/actions/ssh@master
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: beacondevelop.ssh.wpengine.net
          USER: beacondevelop
        with:
          args: |
            git status
            git --help
